export const RoadItem = [
  {
    src: "https://cover.millie.co.kr/service/millie_road/0d354ddfa9a447f6b4bf6ea4a8094f9c.jpeg?w=75&f=webp&q=80",
    gray1: "연재",
    gray2: "총 4화",
    title: "당신의 삶에 불운이 닥칠 때",
    writer: "허미미변호사",
    point1: "· 변호사도 판사에게 혼나는 게 무섭다!",
    point2: "· 드라마와는 조금 다른 현실적인 이야기",
    point3: "· 알아두면 반드시도움되는 든든한 TIP",
  },
  {
    src: "https://cover.millie.co.kr/service/millie_road/a89f328830954e1ab6c685d54ed5cc43.jpeg?w=75&f=webp&q=80",
    gray1: "연재",
    gray2: "총 8화",
    title: "큰 집으로 갈 수 없어 미니멀 라이프",
    writer: "영글음",
    point1: "· 지극히 현실적인 미니멀 라이프 도전기",
    point2: "· 무작정 버린다고 미니멀 라이프는 아니다",
    point3: "· 리얼하고 생생한 일상 속 미니멀 라이프",
  },
  {
    src: "https://cover.millie.co.kr/service/millie_road/9452ccb56d08424690b7e7b87d0367d1.jpeg",
    gray1: "연재",
    gray2: "총 1화",
    title: "낙서연구",
    writer: "문보영",
    point1: "· 작가들은 책 옆에 어떤 낙서를 할까",
    point2: "· 낙서가 작품이 되는 과정을 공개합니다",
    point3: "· 문보영 시인의 새로운 연재 시리즈!",
  },
  {
    src: "https://cover.millie.co.kr/service/millie_road/7d3fcaf5f8224891ad102e3210e7108c.jpeg?w=75&f=webp&q=80",
    gray1: "연재",
    gray2: "총 8화",
    title: "그 남자는 왜 지가 입덧을 했을까",
    writer: "이로부",
    point1: "· 대리 입덧과 육아휴직을 하는 요즘 아빠",
    point2: "· 인생 최고 결과물인 그 아들의 이름은?",
    point3: "· 아재 개그에 피식하고 자존심 상함 주의",
  },
];
